{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMaoQ2b+f8L/XjqVzXs1Zev",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/pierce3215/finances/blob/main/Snowball_Dashboard.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import dash\n",
        "import dash_bootstrap_components as dbc\n",
        "from dash import dcc, html, Input, Output\n",
        "import pandas as pd\n",
        "import plotly.express as px\n",
        "import yfinance as yf\n",
        "\n",
        "# --- Portfolio Data ---\n",
        "portfolio = {\n",
        "    'GOOGL': {'shares': 28, 'cost_basis': 185.45},\n",
        "    'NVDA': {'shares': 100.012031, 'cost_basis': 113.46},\n",
        "    'AMZN': {'shares': 5, 'cost_basis': 237},\n",
        "    'INTC': {'shares': 3, 'cost_basis': 20},\n",
        "    'CRM': {'shares': 29, 'cost_basis': 264.38}\n",
        "}\n",
        "\n",
        "# --- Functions ---\n",
        "def get_portfolio_df():\n",
        "    records = []\n",
        "    total_value = 0\n",
        "    total_cost = 0\n",
        "\n",
        "    for ticker, pos in portfolio.items():\n",
        "        stock = yf.Ticker(ticker)\n",
        "        price = stock.fast_info.get('lastPrice')\n",
        "        if price is None:\n",
        "            continue\n",
        "\n",
        "        shares = pos['shares']\n",
        "        cost_basis = pos['cost_basis']\n",
        "        value = shares * price\n",
        "        invested = shares * cost_basis\n",
        "        gain = value - invested\n",
        "\n",
        "        total_value += value\n",
        "        total_cost += invested\n",
        "\n",
        "        records.append({\n",
        "            'Ticker': ticker,\n",
        "            'Value': value,\n",
        "            'Invested': invested,\n",
        "            'Gain': gain\n",
        "        })\n",
        "\n",
        "    df = pd.DataFrame(records)\n",
        "    df['Allocation'] = df['Value'] / total_value * 100\n",
        "    return df, total_value, total_cost\n",
        "\n",
        "# --- Dash App Setup ---\n",
        "app = dash.Dash(__name__, external_stylesheets=[dbc.themes.DARKLY])\n",
        "app.title = \"Snowball Portfolio Tracker\"\n",
        "\n",
        "app.layout = dbc.Container([\n",
        "    html.Br(),\n",
        "\n",
        "    # --- Top Metrics ---\n",
        "    dbc.Row([\n",
        "        dbc.Col(dbc.Card([\n",
        "            dbc.CardHeader(\"Value\", className=\"text-info\"),\n",
        "            dbc.CardBody([\n",
        "                html.H3(id=\"total-value\", className=\"card-title\"),\n",
        "                html.P(id=\"total-invested\", className=\"card-text\")\n",
        "            ])\n",
        "        ], color=\"dark\", inverse=True), md=3),\n",
        "\n",
        "        dbc.Col(dbc.Card([\n",
        "            dbc.CardHeader(\"Total Profit\", className=\"text-success\"),\n",
        "            dbc.CardBody([\n",
        "                html.H3(id=\"total-gain\", className=\"card-title text-success\"),\n",
        "                html.P(\"\", className=\"card-text\")\n",
        "            ])\n",
        "        ], color=\"dark\", inverse=True), md=3),\n",
        "\n",
        "        dbc.Col(dbc.Card([\n",
        "            dbc.CardHeader(\"IRR\", className=\"text-primary\"),\n",
        "            dbc.CardBody([\n",
        "                html.H3(\"8.51%\", className=\"card-title text-primary\"),\n",
        "                html.P(\"5.93% current holdings\", className=\"card-text\")\n",
        "            ])\n",
        "        ], color=\"dark\", inverse=True), md=3),\n",
        "\n",
        "        dbc.Col(dbc.Card([\n",
        "            dbc.CardHeader(\"Passive Income\", className=\"text-success\"),\n",
        "            dbc.CardBody([\n",
        "                html.H3(\"5.2%\", className=\"card-title text-success\"),\n",
        "                html.P(\"$6,273.73 annually\", className=\"card-text\")\n",
        "            ])\n",
        "        ], color=\"dark\", inverse=True), md=3)\n",
        "    ], className=\"mb-4\"),\n",
        "\n",
        "    # --- Portfolio Breakdown ---\n",
        "    dbc.Row([\n",
        "        dbc.Col(dcc.Graph(id='donut-chart', config={'displayModeBar': False}), md=4),\n",
        "        dbc.Col(html.Div(id='breakdown-table'))\n",
        "    ])\n",
        "], fluid=True)\n",
        "\n",
        "# --- Callbacks ---\n",
        "@app.callback(\n",
        "    [Output('total-value', 'children'),\n",
        "     Output('total-invested', 'children'),\n",
        "     Output('total-gain', 'children'),\n",
        "     Output('donut-chart', 'figure'),\n",
        "     Output('breakdown-table', 'children')],\n",
        "    Input('donut-chart', 'id')\n",
        ")\n",
        "def update_dashboard(_):\n",
        "    df, total_value, total_cost = get_portfolio_df()\n",
        "    gain = total_value - total_cost\n",
        "\n",
        "    fig = px.pie(df, names='Ticker', values='Value', hole=0.5)\n",
        "    fig.update_layout(template=\"plotly_dark\")\n",
        "\n",
        "    table_body = [html.Thead(html.Tr([\n",
        "        html.Th(\"Name\"),\n",
        "        html.Th(\"Value/Invested\"),\n",
        "        html.Th(\"Gain\"),\n",
        "        html.Th(\"Allocation\")\n",
        "    ]))]\n",
        "\n",
        "    rows = []\n",
        "    for _, row in df.iterrows():\n",
        "        gain_color = \"lime\" if row['Gain'] >= 0 else \"red\"\n",
        "        rows.append(html.Tr([\n",
        "            html.Td(row['Ticker']),\n",
        "            html.Td(f\"${row['Value']:,.0f} / ${row['Invested']:,.0f}\"),\n",
        "            html.Td(f\"{row['Gain']:,.2f}\", style={\"color\": gain_color}),\n",
        "            html.Td(f\"{row['Allocation']:.2f}%\")\n",
        "        ]))\n",
        "\n",
        "    table_body.append(html.Tbody(rows))\n",
        "\n",
        "    return (\n",
        "        f\"${total_value:,.2f}\",\n",
        "        f\"${total_cost:,.2f} invested\",\n",
        "        f\"{gain:+,.2f}\",\n",
        "        fig,\n",
        "        dbc.Table(table_body, bordered=True, hover=True, responsive=True, striped=True, class_name=\"table-dark\")\n",
        "    )\n",
        "\n",
        "if __name__ == '__main__':\n",
        "    app.run(debug=True)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 671
        },
        "id": "7pReWSXAAral",
        "outputId": "4dd81f3a-b6df-4dd6-9d28-0c3e84e08e89"
      },
      "execution_count": 9,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "(async (port, path, width, height, cache, element) => {\n",
              "    if (!google.colab.kernel.accessAllowed && !cache) {\n",
              "      return;\n",
              "    }\n",
              "    element.appendChild(document.createTextNode(''));\n",
              "    const url = await google.colab.kernel.proxyPort(port, {cache});\n",
              "    const iframe = document.createElement('iframe');\n",
              "    iframe.src = new URL(path, url).toString();\n",
              "    iframe.height = height;\n",
              "    iframe.width = width;\n",
              "    iframe.style.border = 0;\n",
              "    iframe.allow = [\n",
              "        'accelerometer',\n",
              "        'autoplay',\n",
              "        'camera',\n",
              "        'clipboard-read',\n",
              "        'clipboard-write',\n",
              "        'gyroscope',\n",
              "        'magnetometer',\n",
              "        'microphone',\n",
              "        'serial',\n",
              "        'usb',\n",
              "        'xr-spatial-tracking',\n",
              "    ].join('; ');\n",
              "    element.appendChild(iframe);\n",
              "  })(8050, \"/\", \"100%\", 650, false, window.element)"
            ]
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import dash\n",
        "import dash_bootstrap_components as dbc\n",
        "from dash import dcc, html, Input, Output\n",
        "import pandas as pd\n",
        "import plotly.express as px\n",
        "import yfinance as yf\n",
        "from datetime import datetime\n",
        "import numpy as np\n",
        "\n",
        "# --- Portfolio Data ---\n",
        "portfolio = {\n",
        "    'GOOGL': {'shares': 28, 'cost_basis': 185.45},\n",
        "    'NVDA': {'shares': 100.012031, 'cost_basis': 113.46},\n",
        "    'AMZN': {'shares': 5, 'cost_basis': 237},\n",
        "    'INTC': {'shares': 3, 'cost_basis': 20},\n",
        "    'CRM': {'shares': 29, 'cost_basis': 264.38}\n",
        "}\n",
        "\n",
        "# --- Functions ---\n",
        "def get_portfolio_df():\n",
        "    records = []\n",
        "    total_value = 0\n",
        "    total_cost = 0\n",
        "    dividends = 0\n",
        "\n",
        "    for ticker, pos in portfolio.items():\n",
        "        stock = yf.Ticker(ticker)\n",
        "        price = stock.fast_info.get('lastPrice')\n",
        "        if price is None:\n",
        "            continue\n",
        "\n",
        "        shares = pos['shares']\n",
        "        cost_basis = pos['cost_basis']\n",
        "        value = shares * price\n",
        "        invested = shares * cost_basis\n",
        "        gain = value - invested\n",
        "\n",
        "        # Simulated dividend income (replace with actual data if needed)\n",
        "        dividend_rate = stock.info.get('dividendYield', 0) or 0\n",
        "        annual_dividend = dividend_rate * value\n",
        "        dividends += annual_dividend\n",
        "\n",
        "        total_value += value\n",
        "        total_cost += invested\n",
        "\n",
        "        records.append({\n",
        "            'Ticker': ticker,\n",
        "            'Value': value,\n",
        "            'Invested': invested,\n",
        "            'Gain': gain,\n",
        "            'Dividend': annual_dividend,\n",
        "            'Sector': stock.info.get('sector', 'Unknown')\n",
        "        })\n",
        "\n",
        "    df = pd.DataFrame(records)\n",
        "    df['Allocation'] = df['Value'] / total_value * 100\n",
        "    return df, total_value, total_cost, dividends\n",
        "\n",
        "def get_sector_breakdown(df):\n",
        "    return df.groupby('Sector')['Value'].sum().reset_index()\n",
        "\n",
        "def simulate_historical_growth(df, years=5, rate=0.12):\n",
        "    now = datetime.now()\n",
        "    dates = pd.date_range(end=now, periods=years, freq='Y')\n",
        "    total = df['Value'].sum()\n",
        "    values = [total / ((1 + rate) ** (years - i)) for i in range(years)]\n",
        "    return pd.DataFrame({'Date': dates, 'Value': values})\n",
        "\n",
        "# --- Dash App Setup ---\n",
        "app = dash.Dash(__name__, external_stylesheets=[dbc.themes.DARKLY])\n",
        "app.title = \"Snowball Portfolio Tracker\"\n",
        "\n",
        "app.layout = dbc.Container([\n",
        "    html.Br(),\n",
        "\n",
        "    # --- Top Metrics ---\n",
        "    dbc.Row([\n",
        "        dbc.Col(dbc.Card([\n",
        "            dbc.CardHeader(\"Value\", className=\"text-info\"),\n",
        "            dbc.CardBody([\n",
        "                html.H3(id=\"total-value\", className=\"card-title\"),\n",
        "                html.P(id=\"total-invested\", className=\"card-text\")\n",
        "            ])\n",
        "        ], color=\"dark\", inverse=True), md=3),\n",
        "\n",
        "        dbc.Col(dbc.Card([\n",
        "            dbc.CardHeader(\"Total Profit\", className=\"text-success\"),\n",
        "            dbc.CardBody([\n",
        "                html.H3(id=\"total-gain\", className=\"card-title text-success\"),\n",
        "                html.P(\"\", className=\"card-text\")\n",
        "            ])\n",
        "        ], color=\"dark\", inverse=True), md=3),\n",
        "\n",
        "        dbc.Col(dbc.Card([\n",
        "            dbc.CardHeader(\"IRR\", className=\"text-primary\"),\n",
        "            dbc.CardBody([\n",
        "                html.H3(\"8.51%\", className=\"card-title text-primary\"),\n",
        "                html.P(\"5.93% current holdings\", className=\"card-text\")\n",
        "            ])\n",
        "        ], color=\"dark\", inverse=True), md=3),\n",
        "\n",
        "        dbc.Col(dbc.Card([\n",
        "            dbc.CardHeader(\"Passive Income\", className=\"text-success\"),\n",
        "            dbc.CardBody([\n",
        "                html.H3(id=\"total-dividend\", className=\"card-title text-success\"),\n",
        "                html.P(\"Estimated annually\", className=\"card-text\")\n",
        "            ])\n",
        "        ], color=\"dark\", inverse=True), md=3)\n",
        "    ], className=\"mb-4\"),\n",
        "\n",
        "    # --- Charts ---\n",
        "    dbc.Row([\n",
        "        dbc.Col(dcc.Graph(id='donut-chart', config={'displayModeBar': False}), md=4),\n",
        "        dbc.Col(html.Div(id='breakdown-table'))\n",
        "    ]),\n",
        "\n",
        "    dbc.Row([\n",
        "        dbc.Col(dcc.Graph(id='sector-pie', config={'displayModeBar': False}), md=6),\n",
        "        dbc.Col(dcc.Graph(id='growth-line', config={'displayModeBar': False}), md=6)\n",
        "    ])\n",
        "\n",
        "], fluid=True)\n",
        "\n",
        "# --- Callbacks ---\n",
        "@app.callback(\n",
        "    [Output('total-value', 'children'),\n",
        "     Output('total-invested', 'children'),\n",
        "     Output('total-gain', 'children'),\n",
        "     Output('total-dividend', 'children'),\n",
        "     Output('donut-chart', 'figure'),\n",
        "     Output('breakdown-table', 'children'),\n",
        "     Output('sector-pie', 'figure'),\n",
        "     Output('growth-line', 'figure')],\n",
        "    Input('donut-chart', 'id')\n",
        ")\n",
        "def update_dashboard(_):\n",
        "    df, total_value, total_cost, dividends = get_portfolio_df()\n",
        "    gain = total_value - total_cost\n",
        "    sector_df = get_sector_breakdown(df)\n",
        "    growth_df = simulate_historical_growth(df)\n",
        "\n",
        "    pie_fig = px.pie(df, names='Ticker', values='Value', hole=0.5)\n",
        "    pie_fig.update_layout(template=\"plotly_dark\")\n",
        "\n",
        "    sector_fig = px.pie(sector_df, names='Sector', values='Value', hole=0.3, title='Sector Allocation')\n",
        "    sector_fig.update_layout(template=\"plotly_dark\")\n",
        "\n",
        "    growth_fig = px.line(growth_df, x='Date', y='Value', title='Estimated Portfolio Growth')\n",
        "    growth_fig.update_layout(template=\"plotly_dark\")\n",
        "\n",
        "    table_body = [html.Thead(html.Tr([\n",
        "        html.Th(\"Name\"),\n",
        "        html.Th(\"Value/Invested\"),\n",
        "        html.Th(\"Gain\"),\n",
        "        html.Th(\"Allocation\"),\n",
        "        html.Th(\"Dividend\")\n",
        "    ]))]\n",
        "\n",
        "    rows = []\n",
        "    for _, row in df.iterrows():\n",
        "        gain_color = \"lime\" if row['Gain'] >= 0 else \"red\"\n",
        "        rows.append(html.Tr([\n",
        "            html.Td(row['Ticker']),\n",
        "            html.Td(f\"${row['Value']:,.0f} / ${row['Invested']:,.0f}\"),\n",
        "            html.Td(f\"{row['Gain']:,.2f}\", style={\"color\": gain_color}),\n",
        "            html.Td(f\"{row['Allocation']:.2f}%\"),\n",
        "            html.Td(f\"${row['Dividend']:,.2f}\")\n",
        "        ]))\n",
        "\n",
        "    table_body.append(html.Tbody(rows))\n",
        "\n",
        "    return (\n",
        "        f\"${total_value:,.2f}\",\n",
        "        f\"${total_cost:,.2f} invested\",\n",
        "        f\"{gain:+,.2f}\",\n",
        "        f\"${dividends:,.2f}\",\n",
        "        pie_fig,\n",
        "        dbc.Table(table_body, bordered=True, hover=True, responsive=True, striped=True, class_name=\"table-dark\"),\n",
        "        sector_fig,\n",
        "        growth_fig\n",
        "    )\n",
        "\n",
        "if __name__ == '__main__':\n",
        "    app.run(debug=True)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 671
        },
        "id": "-IISOYqVBOIW",
        "outputId": "6ccf0fd0-f9be-42bc-a461-832d00d53be3"
      },
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "(async (port, path, width, height, cache, element) => {\n",
              "    if (!google.colab.kernel.accessAllowed && !cache) {\n",
              "      return;\n",
              "    }\n",
              "    element.appendChild(document.createTextNode(''));\n",
              "    const url = await google.colab.kernel.proxyPort(port, {cache});\n",
              "    const iframe = document.createElement('iframe');\n",
              "    iframe.src = new URL(path, url).toString();\n",
              "    iframe.height = height;\n",
              "    iframe.width = width;\n",
              "    iframe.style.border = 0;\n",
              "    iframe.allow = [\n",
              "        'accelerometer',\n",
              "        'autoplay',\n",
              "        'camera',\n",
              "        'clipboard-read',\n",
              "        'clipboard-write',\n",
              "        'gyroscope',\n",
              "        'magnetometer',\n",
              "        'microphone',\n",
              "        'serial',\n",
              "        'usb',\n",
              "        'xr-spatial-tracking',\n",
              "    ].join('; ');\n",
              "    element.appendChild(iframe);\n",
              "  })(8050, \"/\", \"100%\", 650, false, window.element)"
            ]
          },
          "metadata": {}
        }
      ]
    }
  ]
}
